name: "VitoMqtt"
description: "Mqtt interface to vcontrold"
version: "0.5"
url: "https://github.com/misery/VitoMqtt/"
slug: "vitomqtt"
init: false
legacy: true
startup: "application"
uart: true
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
image: "aklitzing/vitomqtt"
options:
  DEVICE: "/dev/ttyUSB0"
  MQTT_HOST: null
schema:
  DEVICE: str
  MQTT_HOST: str
