version: '3'

services:
  vitomqtt:
    image: aklitzing/vitomqtt:latest
    container_name: vitomqtt
    devices:
      - /dev/ttyUSB0
    environment:
      - MQTT_HOST=192.168.123.99
      - POLLING=*/5 * * * *
    volumes:
      - ./vcontrold.xml:/etc/vcontrold/vcontrold.xml
      - ./vito.xml:/etc/vcontrold/vito.xml
    restart: always

